# Generated by Django 5.0.1 on 2024-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='c_id',
        ),
    ]
