# Generated by Django 5.0.1 on 2024-04-01 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='webapp.category'),
            preserve_default=False,
        ),
    ]
