# Generated by Django 5.0.1 on 2024-04-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.events')),
                ('items', models.ManyToManyField(to='webapp.item')),
            ],
        ),
    ]
