# Generated by Django 5.0.1 on 2024-04-05 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_package_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package1',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='items',
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Book_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_person', models.IntegerField()),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('book_date', models.DateTimeField()),
                ('address', models.CharField(max_length=250)),
                ('note', models.TextField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.events')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.item'),
            preserve_default=False,
        ),
    ]
