# Generated by Django 5.0.1 on 2024-04-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_package_no_of_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_person',
        ),
    ]
