# Generated by Django 5.0.1 on 2024-04-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_booking_book_time_alter_booking_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_date',
        ),
    ]
