# Generated by Django 5.0.1 on 2024-04-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_booking_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=10),
            preserve_default=False,
        ),
    ]
